clear
set more off

global data "X:\Rosa\data cj"


*******************************************************************************/*
  SED Occupation Paper
 
 Created by: Rosa Castro Zarzur, rcastrozarzur@air.org ; February 3, 2015

 Creating team size variable with data generated by Ahmad
 
********************************************************************************/
import delimited "${data}\teamsize_data_from_Ahmad_v4.csv", clear

replace count=. if count==-1 /* the individual did not work in that award during that year */

replace count=count +1 /* we need to be able to differentiate team size of people that matched that were not funded (team size==0) and people that were funded but works on awards by themselves (team size ==1) */

bysort __employee_id year: egen awards_year=count(count)
bysort __employee_id year: egen team_year=total(count)
gen av_team_year=team_year/awards_year

keep year  __employee_id av_team_year
duplicates drop

bysort __employee_id: egen years=count(av_team_year)
bysort __employee_id: egen  sum_av_team_year=total(av_team_year)
gen av_teamsize = sum_av_team_year/years

bysort __employee_id: egen av2_teamsize=mean(av_team_year)

keep __employee_id av_teamsize 
duplicates drop

tostring __employee_id, replace

save "${data}\teamsize_v4.dta", replace

