create table weicheng.sed_occ_match_notmatch_v1 (
select sed.DRF_ID as ID, PHDINST, PHDDISS, PHDDISS_label, SRCEPRIM, SRCE1ED, SRCESEC, SRCEA, SRCEB, SRCEC, SRCED,
SRCEE, SRCEF, SRCEG, SRCEH, SRCEI, SRCEJ, SRCEK, SRCEL, SRCEM, SRCEN, POSTDOC, PDOCSTAT, PDOCPLAN, PDSTDSUP,
PDEMPLOY, PDOCCODE, PDFORGN, SALARYR, SALARYV, SALMONTH, PDWKPRIM, PDWK1ED, PDWKSEC, PDWK2ED, DEBTLEVL,
PHDCY, SEX, RACE, ASIAN, BLACK, WHITE, HISPANIC, EDFATHER, EDMOTHER, BIRTHPL, PHDMONTH, link.* 
from seddata.sed sed
left join seddata.sed_sm link on link.DRF_ID = sed.DRF_ID
where __link_type_id = 16
);


insert into weicheng.sed_occ_match_notmatch_v1 (
select sed.DRF_ID as ID, PHDINST, PHDDISS, PHDDISS_label, SRCEPRIM, SRCE1ED, SRCESEC, SRCEA, SRCEB, SRCEC, SRCED,
SRCEE, SRCEF, SRCEG, SRCEH, SRCEI, SRCEJ, SRCEK, SRCEL, SRCEM, SRCEN, POSTDOC, PDOCSTAT, PDOCPLAN, PDSTDSUP,
PDEMPLOY, PDOCCODE, PDFORGN, SALARYR, SALARYV, SALMONTH, PDWKPRIM, PDWK1ED, PDWKSEC, PDWK2ED, DEBTLEVL,
PHDCY, SEX, RACE, ASIAN, BLACK, WHITE, HISPANIC, EDFATHER, EDMOTHER, BIRTHPL, PHDMONTH, link.* 
from seddata.sed sed
left join seddata.sed_sm link on link.DRF_ID = sed.DRF_ID
where __link_type_id is null
)
