create table weicheng.sed_occ_link16_v2 (
SELECT e.*, s.DRF_ID, PHDINST, PHDDISS, PHDDISS_label, SRCEPRIM, SRCE1ED, SRCESEC, SRCEA, SRCEB, SRCEC,
SRCED, SRCEE, SRCEF, SRCEG, SRCEH, SRCEI, SRCEJ, SRCEK, SRCEL, SRCEM, SRCEN, POSTDOC, PDOCSTAT, PDOCPLAN,
PDSTDSUP, PDEMPLOY, PDOCCODE, PDFORGN, SALARYR, SALARYV, SALMONTH, PDWKPRIM, PDWK1ED, PDWKSEC, PDWK2ED,
DEBTLEVL, PHDCY, SEX, RACE, ASIAN, BLACK, WHITE, HISPANIC, EDFATHER, EDMOTHER, BIRTHPL, PHDMONTH, PHDFIELD,
TUITREMS, PHDENTRY, PHDENTRY, PHDHBCU, YRSDISST, YRSGRAD, PHDMONTH
FROM starmetricsnew.employee_transaction_11242015 e
left join seddata.sed_sm s on s.__employee_id = e.__employee_id
left join seddata.sed ss on ss.DRF_ID = s.DRF_ID
where __link_type_id = 16
); 

